token_hmac_secret_key = "dfa244ee-587f-43f9-adc5-b727a081d5de"
api_key = "dc1e276a-9eb5-4950-a8bc-c13fe848154a"
allowed_origins = [ "*" ]
client_anonymous = true

[[namespaces]]
name = "e2e-tests"
anonymous = true
