version: "3"

services:

  centrifugo:
    image: centrifugo/centrifugo:v4.1
    command:
      - centrifugo
      - --config=/usr/local/etc/centrifugo.toml
    ports:
      - 8000:8000
    volumes:
      - ./centrifugo.toml:/usr/local/etc/centrifugo.toml:ro
